---
title: "FlexDashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r include=FALSE}
data("instacart")

aisles_summary= 
  instacart |> 
  count(aisle, sort=TRUE)

aisles_summary |> 
  head(10) 
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
aisles_summary |>
  filter(n > 10000) |>
  mutate(aisle = fct_reorder(aisle, n)) |>
  mutate(hover = paste0("Aisle: ", aisle, "<br>Orders: ", n)) |>
  plot_ly(
    x = ~n, y = ~aisle, type = "bar", orientation = "h",
    text = ~hover, hoverinfo = "text",
    color = ~aisle, colors = "viridis", showlegend = FALSE
  ) |>
  layout(
    title = "Number of Items Ordered by Aisle (>10,000 orders)",
    xaxis = list(title = "Number of Items Ordered"),
    yaxis = list(
      title = list(text = "Aisle", standoff = 30) 
    ),
    margin = list(l = 100, r = 20, t = 50, b = 50) 
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
instacart |>
  filter(department %in% c("produce", "dairy eggs", "snacks")) |>
  count(department, order_hour_of_day, name = "orders") |>
  plot_ly(
    x = ~order_hour_of_day,
    y = ~orders,
    color = ~department,
    type = "scatter",
    mode = "lines+markers",
    colors = c("#4E79A7", "#F28E2B", "#E15"))|>
  layout(
    title = "Ordering Trends Throughout the Day",
    xaxis = list(title = "Hour of Day (0–23)"),
    yaxis = list(title = "Number of Orders"),
    legend = list(orientation = "v"))

```

### Chart C

```{r}
instacart |> 
  filter(department %in% c("produce", "dairy eggs", "snacks"))|>   mutate(department =fct_reorder(department,add_to_cart_order)) |> 
  plot_ly(
    x = ~department,
    y = ~add_to_cart_order,
    color = ~department,
    type = "violin",
    colors = c("#4E79A7", "#F28E2B", "#E15"),
    box = list(visible = TRUE),
    meanline = list(visible = TRUE),
    opacity = 0.8
  ) |>
  layout(
    title = "Cart Order Distribution",
    xaxis = list(title = "Department"),
    yaxis = list(title = "Add-to-Cart Order")
  )

```
